import { Character, Quest, UserStats, Badge, Discovery } from '../types';

export const MOCK_CHARACTERS: Character[] = [
  {
    id: 'birdo',
    name: 'Birdo',
    tagline: 'Wildlife & Feathered Friends Explorer',
    domain: 'Birds, animals, insects and wildlife',
    personality: 'Energetic, curious, playful',
    bio: 'Birdo has an eagle eye for creature footprints, birdcalls, and critters hiding in plain sight. Always ready to hop through parks and woods!',
    avatarColor: '#10B981',
    badgeEmoji: '🐦',
    themeColor: {
      bg: 'bg-emerald-50',
      border: 'border-emerald-200',
      text: 'text-emerald-800',
      badge: 'bg-emerald-500',
      bubble: 'bg-emerald-100 text-emerald-950',
    },
    sampleQuestions: [
      'Why do crows make so much noise in the morning?',
      'How do squirrels remember where they buried nuts?',
      'What kind of birds are most active around sunset?',
      'How can I spot insect tracks on trees?',
    ],
    sampleOutdoorActivities: [
      "Next time you're outside, stand still for 30 seconds and count how many unique bird calls you hear!",
      'Look under a damp fallen branch to discover busy earthworms and isopods!',
      'Check tree bark at eye level for hidden beetle burrows or butterfly chrysalises.',
    ],
  },
  {
    id: 'flora',
    name: 'Flora',
    tagline: 'Botanist & Forest Whisperer',
    domain: 'Plants, trees, flowers and nature',
    personality: 'Calm, friendly, knowledgeable',
    bio: 'Flora knows every leaf pattern, moss species, and blooming season. She turns every sidewalk dandelion and grand oak into a botanical masterclass.',
    avatarColor: '#22C55E',
    badgeEmoji: '🌿',
    themeColor: {
      bg: 'bg-green-50',
      border: 'border-green-200',
      text: 'text-green-800',
      badge: 'bg-green-500',
      bubble: 'bg-green-100 text-green-950',
    },
    sampleQuestions: [
      'Why do leaves change color in autumn?',
      'How do roots break through concrete pavements?',
      'What is the purpose of pinecone scales opening and closing?',
      'How can I tell the age of a tree without cutting it down?',
    ],
    sampleOutdoorActivities: [
      'Touch the bark of three different trees and notice how their texture and temperature differ.',
      'Gently turn over a green leaf to see the intricate vein networks carrying water.',
      'Find a flower bud and check if it faces toward the direction of sunlight.',
    ],
  },
  {
    id: 'atlas',
    name: 'Atlas',
    tagline: 'Architect & Chronicle Keeper',
    domain: 'Monuments, architecture, history and landmarks',
    personality: 'Adventurous, historical, storyteller',
    bio: 'Atlas reads cities like ancient manuscripts. From foundation cornerstones to architectural arches, every facade tells a story of generations past.',
    avatarColor: '#F59E0B',
    badgeEmoji: '🏛️',
    themeColor: {
      bg: 'bg-amber-50',
      border: 'border-amber-200',
      text: 'text-amber-800',
      badge: 'bg-amber-500',
      bubble: 'bg-amber-100 text-amber-950',
    },
    sampleQuestions: [
      'Why do old buildings have decorative gargoyles and keystones?',
      'How do stone arches support huge weights without collapsing?',
      'What do foundation cornerstone dates tell us about urban expansion?',
      'Why are cobblestones arranged in fan-shaped patterns?',
    ],
    sampleOutdoorActivities: [
      'Find the oldest building on your street and look for date carvings or historic plaque markers.',
      'Look up at the rooflines and window arches of two neighbouring buildings to spot different architectural eras.',
      'Search for a repurposed historic element, like an old tram track or iron gate.',
    ],
  },
  {
    id: 'munch',
    name: 'Munch',
    tagline: 'Forager & Culinary Cartographer',
    domain: 'Food, ingredients, edible plants and food culture',
    personality: 'Funny, enthusiastic and curious',
    bio: 'Munch is obsessed with how food connects us to soil and geography. Spices, wild berries, street vendors, and heritage grain recipes make Munch smile!',
    avatarColor: '#F97316',
    badgeEmoji: '🫐',
    themeColor: {
      bg: 'bg-orange-50',
      border: 'border-orange-200',
      text: 'text-orange-800',
      badge: 'bg-orange-500',
      bubble: 'bg-orange-100 text-orange-950',
    },
    sampleQuestions: [
      'Where do wild berries grow naturally in cities?',
      'How did ancient civilizations preserve fruits before refrigeration?',
      'Why do aromatic herbs release strong scent when gently rubbed?',
      'What makes coffee beans taste different depending on the elevation they grow?',
    ],
    sampleOutdoorActivities: [
      'Visit an outdoor fruit stand or herb bed and identify three plants by scent alone.',
      'Observe a wild rosemary or mint bush and examine the essential oil glands on its leaves.',
      'Take a photo of an edible garden plant and learn its heritage origin story.',
    ],
  },
  {
    id: 'nova',
    name: 'Nova',
    tagline: 'Cosmic Naturalist & Earth Scientist',
    domain: 'General knowledge, science, geography and random discoveries',
    personality: 'Smart, curious and slightly playful',
    bio: 'Nova connects the micro to the macro — explaining how pebble patterns reflect ancient rivers and how cloud formations forecast solar radiation.',
    avatarColor: '#8B5CF6',
    badgeEmoji: '✨',
    themeColor: {
      bg: 'bg-purple-50',
      border: 'border-purple-200',
      text: 'text-purple-800',
      badge: 'bg-purple-500',
      bubble: 'bg-purple-100 text-purple-950',
    },
    sampleQuestions: [
      'How are smooth river stones shaped by turbulent water flow?',
      'Why do shadows change length and angle throughout the day?',
      'What causes morning dew drops to form perfect spheres?',
      'How does urban microclimate affect local wind speeds?',
    ],
    sampleOutdoorActivities: [
      'Check the shadow of a flagpole or tree at noon and compare it 2 hours later.',
      'Find three distinct rock types on your path and look for mineral crystals under sunlight.',
      'Watch cloud drift for 60 seconds to detect upper atmosphere wind currents.',
    ],
  },
];

export const MOCK_USER_STATS: UserStats = {
  id: 'usr_partner_01',
  username: 'eco_wanderer',
  displayName: 'Vaibhav S.',
  level: 8,
  currentXp: 2430,
  nextLevelXp: 3000,
  coins: 580,
  currentStreak: 12,
  longestStreak: 18,
  totalDistanceKm: 32.7,
  totalExplorationTimeSeconds: 43200, // 12 hours
  discoveriesCount: 27,
  questsCompletedCount: 42,
  todayDistanceKm: 1.4,
  todayExplorationTimeSeconds: 1560, // 26 mins
  todayTargetDistanceKm: 2.0,
};

export const MOCK_QUESTS: Quest[] = [
  {
    id: 'quest_birdo_01',
    title: 'Spot a Feathered Neighbor',
    description: 'Find a wild bird resting in a tree, perched on a fence, or foraging on the ground. Capture a clear photo!',
    characterId: 'birdo',
    category: 'bird',
    xpReward: 50,
    coinReward: 10,
    durationMinutes: 120,
    expiresAt: new Date(Date.now() + 102 * 60 * 1000).toISOString(), // 1h 42m remaining
    isDaily: true,
    status: 'available',
    targetHint: 'Parks, garden fences, high branches, or rooftops',
    iconEmoji: '🐦',
  },
  {
    id: 'quest_flora_01',
    title: 'Discover a Flowering Tree or Wild Plant',
    description: 'Take a close-up picture of a flowering plant or vibrant tree leaf. Notice the petal structure and leaf veins!',
    characterId: 'flora',
    category: 'plant',
    xpReward: 40,
    coinReward: 10,
    durationMinutes: 180,
    expiresAt: new Date(Date.now() + 160 * 60 * 1000).toISOString(),
    isDaily: true,
    status: 'available',
    targetHint: 'Sidewalk garden beds, park trails, flowering shrubs',
    iconEmoji: '🌸',
  },
  {
    id: 'quest_atlas_01',
    title: 'Find a Historic Landmark or Arch',
    description: 'Locate a notable statue, commemorative plaque, historic building facade, or archway in your neighborhood.',
    characterId: 'atlas',
    category: 'monument',
    xpReward: 60,
    coinReward: 15,
    durationMinutes: 240,
    expiresAt: new Date(Date.now() + 210 * 60 * 1000).toISOString(),
    isDaily: false,
    status: 'available',
    targetHint: 'Town squares, old brick structures, heritage monuments',
    iconEmoji: '🏛️',
  },
  {
    id: 'quest_munch_01',
    title: 'Locate a Fresh Herb or Fruit Tree',
    description: 'Find an edible herb (like mint, rosemary, basil) or fruit tree growing outdoors and capture its vibrant colors.',
    characterId: 'munch',
    category: 'plant',
    xpReward: 45,
    coinReward: 10,
    durationMinutes: 150,
    expiresAt: new Date(Date.now() + 90 * 60 * 1000).toISOString(),
    isDaily: false,
    status: 'available',
    targetHint: 'Community gardens, botanical pots, fruit orchards',
    iconEmoji: '🌿',
  },
  {
    id: 'quest_nova_01',
    title: 'Find an Intriguing Geological Pattern',
    description: 'Look for an eye-catching mineral formation, textured boulder, pebble arrangement, or weathered rock surface.',
    characterId: 'nova',
    category: 'discovery',
    xpReward: 55,
    coinReward: 15,
    durationMinutes: 180,
    expiresAt: new Date(Date.now() + 145 * 60 * 1000).toISOString(),
    isDaily: false,
    status: 'available',
    targetHint: 'Riverbanks, garden rockeries, textured stones',
    iconEmoji: '🪨',
  },
];

export const MOCK_BADGES: Badge[] = [
  {
    id: 'badge_first_exploration',
    title: 'First Exploration',
    description: 'Stepped outside and recorded your very first outdoor walk.',
    iconEmoji: '🌱',
    category: 'exploration',
    rarity: 'common',
    unlockedAt: '2026-09-15',
    isUnlocked: true,
  },
  {
    id: 'badge_first_discovery',
    title: 'First Discovery',
    description: 'Photographed and identified your first real-world object.',
    iconEmoji: '📸',
    category: 'discovery',
    rarity: 'common',
    unlockedAt: '2026-09-15',
    isUnlocked: true,
  },
  {
    id: 'badge_wildlife_explorer',
    title: 'Wildlife Explorer',
    description: 'Identified 10 wild animals or bird species with Birdo.',
    iconEmoji: '🐦',
    category: 'discovery',
    rarity: 'rare',
    unlockedAt: '2026-09-24',
    isUnlocked: true,
    progressCurrent: 10,
    progressTarget: 10,
  },
  {
    id: 'badge_nature_explorer',
    title: 'Nature Explorer',
    description: 'Cataloged 15 distinct plants, trees, and flowers with Flora.',
    iconEmoji: '🌿',
    category: 'discovery',
    rarity: 'rare',
    unlockedAt: '2026-09-29',
    isUnlocked: true,
    progressCurrent: 15,
    progressTarget: 15,
  },
  {
    id: 'badge_history_hunter',
    title: 'History Hunter',
    description: 'Discovered 5 historic landmarks or architecture monuments with Atlas.',
    iconEmoji: '🏛️',
    category: 'discovery',
    rarity: 'rare',
    unlockedAt: '2026-10-02',
    isUnlocked: true,
    progressCurrent: 5,
    progressTarget: 5,
  },
  {
    id: 'badge_7_day_streak',
    title: '7 Day Explorer',
    description: 'Maintained a 7-day consecutive outdoor exploration streak.',
    iconEmoji: '🔥',
    category: 'streak',
    rarity: 'epic',
    unlockedAt: '2026-09-28',
    isUnlocked: true,
    progressCurrent: 12,
    progressTarget: 7,
  },
  {
    id: 'badge_touch_grass_master',
    title: 'TouchGrass Master',
    description: 'Log 50.0 kilometers of total outdoor exploration.',
    iconEmoji: '🌎',
    category: 'mastery',
    rarity: 'legendary',
    isUnlocked: false,
    progressCurrent: 32.7,
    progressTarget: 50.0,
  },
];

export const MOCK_RECENT_DISCOVERY: Discovery | undefined = undefined;

export const MOCK_DISCOVERY_GALLERY: Discovery[] = [];
